### ISSUE TITLE
Support for Java8 and new features such as lambdas and method references

### ISSUE THREAD

**Issue by isakkarlsson** [bronto/javasphinx#35]
New syntax introduced in Java 8 such as lambdas and method references are not supported.

Experimental support have been added to `javalang` package used for parsing (https://github.com/c2nes/javalang/pull/18)

Perhaps an *experimental* build could be provided with these recent changes?

**Comment by c2nes** [comment]
Hi Isak, is there new functionality which you think Javasphinx could expose for Java 8 projects? Or are you just interested in a release of Javasphinx which can process Java 8 projects (by using the newer version of javalang)?

**Comment by isakkarlsson** [comment]
Hi!

I'm basically just after a new release of Javasphinx that can process Java 8 projects by using the newer (unfortunately unreleased) version of `javalang`.

Since I could of course build the two from source, I mainly created this issue to ensure I could track the progress.

**Comment by c2nes** [comment]
Hey @isakkarlsson, I just published a 0.10.0 release of `javalang` and a 0.9.13 release of `javasphinx` which uses it. These should include the new Java 8 functionality. Let me know if you run into any issues.

**Comment by isakkarlsson** [comment]
Perfect! Will try it soon!

**Comment by trustin** [comment]
Pure awesomeness! @isakkarlsson, could you please come back to us to tell if there's any issue with Java 8 code?

**Comment by wjohnson5** [comment]
Hey, it seems this will throw an error if an interface has a 'default' method:
ERROR:root:Syntax error in /some/path/MyInterface.java: Expected type at default line 28, character 3

**Comment by manoelcampos** [comment]
It really throws an exception when a Java interface has a default method. See the example for the class below:

```java
public interface UniquelyIdentificable extends Identificable {
    static String getUid(int brokerId, int id) {
        return brokerId + "-" + id;
    }

    String getUid();
}
```
_ERROR:root:Syntax error in UniquelyIdentificable .java: Expected ';' at return line 21, character 9_

javalang 0.10.1 already supports Interface's default methods.

**Comment by manoelcampos** [comment]
It is in fact raising an exception when an interface has default or static methods.
Here an example:

```java
public interface MyInterface {
    String getId();
    String getBrokerId();
    default String getUid() {
        return getBrokerId() + "-" + getId();
    }

    static String getUid(String brokerId, String id) {
        return brokerId + "-" + id;
    }
    
}
```

ERROR:root:Syntax error in MyInterface.java: Expected ';' at return line 21, character 9

The javalang 0.10.0 didn't fixed that.
