### ISSUE TITLE
Cache file creation fails on Windows

### ISSUE THREAD

**Issue by trustin** [bronto/javasphinx#36]
Please see [here](https://github.com/bronto/javasphinx/blob/master/javasphinx/apidoc.py#L164).

Could we stop using ':' to replace a file separator so that it runs on Windows? Windows does not allow ':' in a file name. When a absolute path is given in '-c' option, the cache directory path already contains ':' in it (e.g. C:\...), so you need to replace any existing colons in the path as well.

**Comment by c2nes** [comment]
Thanks @trustin! I just pushed a change which I hope addresses this. Let me know if you run  into any other issues. I don't have a Windows machine readily available for testing so I'm very interested in any other problems you run into.

**Comment by trustin** [comment]
Thanks! Looks good to me. :+1:
