### ISSUE TITLE
What version of python does javasphinx require?

### ISSUE THREAD

**Issue by ryantheleach** [bronto/javasphinx#37]

**Comment by c2nes** [comment]
javasphinx should run with Python 2.6.x or 2.7.x. Some work would need to be done to make it compatible with 3.x.

**Comment by ryantheleach** [comment]
Cheers, I tried installing javasphinx using both pip and easyinstall on windows, on both 2.7 and 3.5 and ran into issues with libxml2 dependencies so wasn't entirely sure what was going on so figured I'd ask to check my sanity.

**Comment by moigagoo** [comment]
Hi! I've added Python 3 support in https://github.com/bronto/javasphinx/pull/39.

**Comment by c2nes** [comment]
Python 3 support has been released in 0.9.14. If there's issues with lxml in the future its possible to have `javasphinx-apidoc` use an alternate parser by providing the `-p` flag. If you can get javasphinx installed without lxml (from source or using `pip install --no-deps`) you can install any other parser [supported by BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser).
