### ISSUE TITLE
External Javadoc method reference doesn't work

### ISSUE THREAD

**Issue by wjohnson5** [bronto/javasphinx#40]
I'm trying to use :java:ref:`Class.method(ArgClass)` to link to external Javadocs for a specific method.
However, in Java 8 Javadocs use #method-ArgClass-, not #method(ArgClass), so it's not working 
(See https://bugs.openjdk.java.net/browse/JDK-8144118). Can the refs be changed to Java 8 Javadoc links, or can it be an option (either Java < 8 or Java >= 8)?

**Comment by c2nes** [comment]
I've added a new external doc type called "javadoc8" which should hopefully fix this issue. See http://bronto-javasphinx.readthedocs.io/en/latest/#configuration for updated documentation. I've also updated the built-in doc sources for the JRE to point to the Java 8 versions.
