### ISSUE TITLE
Javasphinx throws error if an interface has a default method defined

### ISSUE THREAD

**Issue by zero57** [bronto/javasphinx#42]
Running javasphinx will throw an error if you have an interface with a 'default' method defined

    ERROR:root:Syntax error in /my/path/interface.java: Expected type at default line 486, character 5

**Comment by travisspencer** [comment]
This seems to be a total blocker for anyone wanting to use Javasphinx with Java 8 code.

**Comment by c2nes** [comment]
@zero57 could you tell me what version of javasphinx and javalang you are using?

**Comment by travisspencer** [comment]
I got this error using javasphinx 0.9.13 and javalang 0.10.0

**Comment by roipoussiere** [comment]
Same problem here, using javasphinx 0.9.13.

Here is some problematic parts of my source code:

- [default void ClassName(){}](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/contents/plugins/events/EditorEvents.java#L10) ;
- [public static void ClassName() {}](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/utils/StorageSaver.java#L21).

**Comment by roipoussiere** [comment]
Actually it's a problem with Javalang:

See [here](https://github.com/bronto/javasphinx/blob/master/javasphinx/apidoc.py#L185):

    try:
        ast = javalang.parse.parse(source)
    except javalang.parser.JavaSyntaxError, e:
        util.error('Syntax error in %s: %s', source_file, format_syntax_error(e))

**Comment by c2nes** [comment]
Thank you for diagnosing this @roipoussiere. I've released a version 0.10.1 of _javalang_ which I hope resolves this issue. Please let me know if there are still issues.

**Comment by c2nes** [comment]
I've also released version 0.9.14 of javasphinx which bumps the javalang dependency to 0.10.1.

**Comment by roipoussiere** [comment]
Thank you!
