### ISSUE TITLE
Fails to compile on OSX

### ISSUE THREAD

**Issue by doridori** [bronto/javasphinx#44]
...gives `ld: library not found for -lrt` when installing via `pip`. Works fine on Ubuntu.

Aware that osx does not have `librt` - is it actually used by javasphinx?

**Comment by c2nes** [comment]
javasphinx itself doesn't have any native code so it wouldn't be the direct cause of this. I would be mostly likely to suspect lxml (brought in as a dependency). Could you provide the full output from attempting to install?

**Comment by c2nes** [comment]
If it is lxml you might try a different parser. See my comment on #37.

**Comment by doridori** [comment]
I ended up using docker in the end, which has librt. Would paste output here but `pip` is borked on my machine this morning and dont have time to mess around with it!

**Comment by c2nes** [comment]
Okay, no problem. I installed on OS X without issue a couple days ago in a fresh virtualenv so I'm going to close this out for now. Feel free to re-open if you run into this problem again.
