### ISSUE TITLE
4 column based index found

### ISSUE THREAD

**Issue by dmitriid** [bronto/javasphinx#48]
### System

Mac OS X 10.11.6
Python 2.7.10
Sphinx v1.4.6
javasphinx 0.9.13

### Problem

Everything works as expected. However, when generating documentation sphinx reports the following:

```
WARNING: 4 column based index found. 
It might be a bug of extensions you use: 
[('single', u'done() (Java method)', u'<method_name>', '')]
```

The documentation is still generated though

**Comment by dmitriid** [comment]
woohoo!

**Comment by jfeick** [comment]
When will a new Version of javasphinx be released? Sadly the latest version from pypi (Sep. 30th) does not include the commit 67e1756.

**Comment by c2nes** [comment]
Sorry for the delay. I've just uploaded version 0.9.15 which includes this fix.
